web:
  build: .
  dockerfile: Dockerfile-development
  links:
   - db
  ports:
   - "8000:8000"
  volumes:
   - .:/usr/src/app/
  environment:
   NODE_ENV: development 
   MONGO_URL: mongodb://admin:iloveGod4ever@ds145245.mlab.com:45245/heroku_q3b2tpgf
db:
  image: mongo:latest
  ports:
   - "45245:45245"

